/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_az_jni_DemoJni */

#ifndef _Included_cn_az_jni_DemoJni
#define _Included_cn_az_jni_DemoJni
#ifdef __cplusplus
extern "C"
{
#endif
    /*
     * Class:     cn_az_jni_DemoJni
     * Method:    say
     * Signature: ()V
     */
    JNIEXPORT void JNICALL jni_native_say(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif