version: "3"

dotenv:
  - "project.env"

tasks:
  lib:
    cmds:
      - cd libmyrica
      - cmake && make
  native:
    cmds:
      - mvn -Pnative spring-boot:build-image -DskipTests
  version:
    cmds:
      - "mvn versions:set -DnewVersion=${VERSION}"
      - mvn versions:commit
