// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello/hello.proto

package cn.az.code.grpc.hello.proto;

public interface RequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:hello.Request)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     *
     * @return The id.
     */
    java.lang.String getId();

    /**
     * <code>string id = 1;</code>
     *
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString getIdBytes();

    /**
     * <code>string msg = 2;</code>
     *
     * @return The msg.
     */
    java.lang.String getMsg();

    /**
     * <code>string msg = 2;</code>
     *
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString getMsgBytes();

    /**
     * <code>string date = 3;</code>
     *
     * @return The date.
     */
    java.lang.String getDate();

    /**
     * <code>string date = 3;</code>
     *
     * @return The bytes for date.
     */
    com.google.protobuf.ByteString getDateBytes();
}
