// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello/hello.proto

package cn.az.code.hello.proto;

public final class Hello {
    private Hello() {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_hello_Request_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_hello_Request_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_hello_Response_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_hello_Response_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
        descriptor;

    static {
        java.lang.String[] descriptorData = {
            "\n\021hello/hello.proto\022\005hello\"0\n\007Request\022\n\n" +
                "\002id\030\001 \001(\t\022\013\n\003msg\030\002 \001(\t\022\014\n\004date\030\003 \001(\t\"%\n\010" +
                "Response\022\014\n\004code\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t2;\n\014H" +
                "elloService\022+\n\010SayHello\022\016.hello.Request\032" +
                "\017.hello.ResponseB#\n\030cn.az.myrica.hello.p" +
                "rotoB\005HelloP\001b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[]{
                });
        internal_static_hello_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
        internal_static_hello_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_hello_Request_descriptor,
            new java.lang.String[]{"Id", "Msg", "Date",});
        internal_static_hello_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
        internal_static_hello_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_hello_Response_descriptor,
            new java.lang.String[]{"Code", "Msg",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
