// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello/hello.proto

package cn.az.code.hello.proto;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hello.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string msg = 2;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
