/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_az_code_jni_HelloJni */

#ifndef _Included_cn_az_code_jni_HelloJni
#define _Included_cn_az_code_jni_HelloJni
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     cn_az_code_jni_HelloJni
   * Method:    sayHello
   * Signature: ()V
   */
  JNIEXPORT void JNICALL Java_cn_az_code_jni_HelloJni_sayHello(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
